TheProject.ReportWebApplication/Controllers/FacilityController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TheProject.Data;
using TheProject.ReportGenerator;
using TheProject.ReportWebApplication.Models;
using TheProject.ReportWebApplication.Services;
using System.Data.Entity;
using System.Net;
using System.Net.Mime;
using System.IO;
using System.IO.Compression;
using System.Configuration;
using TheProject.ReportWebApplication.Utilities;

namespace TheProject.ReportWebApplication.Controllers
{
    public class FacilityController : BaseController
    {
        #region Properties
        private FacilityService facilityService;
        int _defaultPageSize = 20;

        #endregion

        #region Constructor
        public FacilityController()
        {
            this.facilityService = new FacilityService();
        }
        #endregion

        #region Methods

        // GET: Facility
        public ActionResult Index(int? page)
        {
            List<Facility> facilities = GetSubmittedFacilities();

            int currentPageIndex = page.HasValue ? page.Value - 1 : 0;
            IPagedList<Facility> providersListPaged = facilities.ToPagedList(currentPageIndex, _defaultPageSize);

            List<string> regions = facilities.Select(d => d.Region).Distinct().ToList();

            ViewBag.Regions = new SelectList(regions);

            return View(providersListPaged);
        }

        private List<Facility> GetSubmittedFacilities()
        {
            using (ApplicationUnit unit = new ApplicationUnit())
            {
                var dbfacilities = unit.Facilities.GetAll()
                                      .Include(b => b.Buildings)
                                      .Include(d => d.DeedsInfo)
                                      .Include(p => p.ResposiblePerson)
                                      .Include("Location.GPSCoordinates")
                                      .Include("Location.BoundryPolygon")
                                      .Where(ss => ss.Status == "Submitted")
                                      .ToList();
                List<Facility> facilities = new List<Facility>();
                foreach (var item in dbfacilities)
                {
                    facilities.Add(new Facility
                    {
                        ClientCode = item.ClientCode,
                        SettlementType = item.SettlementType,
                        Zoning = item.Zoning,
                        Region = item.Location.Region
                    });
                }
                return facilities;
            }
        }

        // GET: Facility/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult DownloadFacility(string clientCode)
        {
            FacilityReport facilityReport = new FacilityReport();
            ApplicationUnit unit = new ApplicationUnit();
            Model.Facility dbFacility = unit.Facilities.GetAll()
                                        .Include(b => b.Buildings)
                                        .Include(d => d.DeedsInfo)
                                        .Include(c => c.Portfolio)
                                        .Include(p => p.ResposiblePerson)
                                        .Include("Location.GPSCoordinates")
                                        .Include("Location.BoundryPolygon")
                                        .Where(f => f.ClientCode.ToLower() == clientCode.ToLower()).FirstOrDefault();
            if (dbFacility == null)
            {
                return RedirectToAction("Index");
            }

            Model.OriginalData dbOriginalData = unit.OriginalDatas.GetAll()
                .Where(o => o.VENUS_CODE.Trim().ToLower()
                == dbFacility.ClientCode.Trim().ToLower())
                .FirstOrDefault();

            string filePath = facilityReport.GenerateFacilityReport(dbFacility, dbOriginalData);

            using (var webClient = new WebClient())
            {
                if (!System.IO.File.Exists(filePath))
                {
                    return null;
                }
                byte[] file = webClient.DownloadData(filePath);
                DeleteAllFile();
                return File(file, MediaTypeNames.Application.Pdf);
            }
        }

        // GET: Facility/Edit/5
        [HttpPost]
        public ActionResult DownloadAllFacility([Bind(Include = "Region")] Facility facility)
        {

            if (string.IsNullOrEmpty(facility.Region))
            {
                ModelState.AddModelError("", "Please Select Region.");
                return View(facility);

            }
            FacilityReport facilityReport = new FacilityReport();
            ApplicationUnit unit = new ApplicationUnit();

            List<Model.Facility> dbFacilities = unit.Facilities.GetAll()
                                        .Include(b => b.Buildings)
                                        .Include(d => d.DeedsInfo)
                                        .Include(p => p.ResposiblePerson)
                                        .Include("Location.GPSCoordinates")
                                        .Include("Location.BoundryPolygon")
                                        .Where(ss => ss.Status == "Submitted" && ss.Location.Region.Trim().ToLower() == facility.Region.Trim().ToLower())
                                        .ToList();

            if (dbFacilities.Count() == 0)
            {
                ModelState.AddModelError("", "No Facilities Found For Selected Region.");
                return null;
            }
            else
            {
                using (var memoryStream = new MemoryStream())
                {
                    using (ZipArchive ziparchive = new ZipArchive(memoryStream, ZipArchiveMode.Create, true))
                    {
                        foreach (var item in dbFacilities)
                        {
                            Model.OriginalData dbOriginalData = unit.OriginalDatas.GetAll().Where(o => o.VENUS_CODE.Trim().ToLower() == item.ClientCode.Trim().ToLower()).FirstOrDefault();
                            string filePath = facilityReport.GenerateFacilityReport(item, dbOriginalData);
                            ziparchive.CreateEntryFromFile(filePath, item.ClientCode + ".pdf");
                        }
                    }
                    DeleteAllFile();
                    return File(memoryStream.ToArray(), "application/zip", "facilities.zip");
                }
            }
        }

        private void DeleteAllFile()
        {

            string _currpath = ConfigurationManager.AppSettings["ReportsPath"];
            DirectoryInfo di = new DirectoryInfo(_currpath);
            foreach (FileInfo file in di.GetFiles())
            {
                file.Delete();
            }

        }

        public ViewResultBase Search(string search)
        {
            const int currentPageIndex = 0;
            List<Facility> facilities = GetSubmittedFacilities();

            if (!string.IsNullOrEmpty(search))
            {
                facilities = facilities.OrderBy(s => s.ClientCode)
                    .Where(
                        s =>
                            s.ClientCode.ToUpper().Contains(search.ToUpper())).ToList();
            }
            IPagedList<Facility> providersListPaged = facilities.ToPagedList(currentPageIndex,
               _defaultPageSize);

            List<string> regions = facilities.Select(d => d.Region).Distinct().ToList();
            ViewBag.Regions = new SelectList(regions);

            if (Request.IsAjaxRequest())
                return PartialView("Index", providersListPaged);
            return View("Index", providersListPaged);
        }
        #endregion
    }
}

TheProject.ReportWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ZCS Asset Management</title>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script> -->
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <!-- <script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
     <script src="~/Scripts/jquery.gauge.js"></script> -->

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fontawesome")
    @Scripts.Render("~/bundles/modernizr")
</head>
        <body>
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container" style="float: left; padding: 10px; width:100%">
                    <div class="row">
                        <button class="navbar-toggler isNotMobile" style="height: 25px;" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent"
                                aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="fa fa-bars" aria-hidden="true"></i>
                        </button>
                        <div class="col-lg-2 col-md-12 col-sm-12 center-header">
                            <img height="70px" width="150px" src="~/Content/ic_app.png">
                            <label class="header isNotMobile">ZCS Asset Management</label>
                            @Html.ActionLink("Logout", "Logout", "Home", new { @class = "logout isNotMobile" })
                        </div>
                        <div class="col-lg-8 col-md-12 col-sm-12 isMobile">
                            <label class="header">ZCS Asset Management</label>
                        </div>
                        <div class="col-lg-2 col-md-12 col-sm-12 isMobile">
                            @Html.ActionLink("Logout", "Logout", "Home", new { @class = "logout" })
                        </div>
                    </div>

                    <ul class="collapse list" style="overflow: hidden; width: auto; height: calc(100vh - 65px); list-style: none;" id="navbarToggleExternalContent">
                        <li><label class="waves-effect waves-block menu-item"><i class="fa fa-home sidebar-icon"></i><span class="primery-color">@Html.ActionLink("Dashboard", "Index", "Home")</span></label> </li>
                        <li><label class="waves-effect waves-block menu-item"><i class="fa fa-file-o sidebar-icon"></i><span class="primery-color">@Html.ActionLink("Reports", "Index", "Facility")</span> </label> </li>
                    </ul>
                </div>
            </div>
            <div class="container body-content">
            </div>
            <div id="wrapper" class="row">
                <!-- Sidebar -->
    <div id="sidebar-wrapper" class="sidebar col-lg-2 col-md-2 col-sm-12">
        <div class="menu">
            <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: calc(100vh - 65px);">
                <ul class="list" style="overflow: hidden; width: auto; height: calc(100vh - 65px); list-style: none;">
                    <li>
                        <div class="user-info">
                            <div class="image"><a class=" waves-effect waves-block" href="profile.html"><img alt="User" height="100px" width="100px" src="~/Content/profile_pic.jpg"></a></div>
                            <div class="detail">
                                <h4>Administrator</h4>
                            </div>
                        </div>
                    </li>
                    <li style="margin-bottom: -10px;"><label class="waves-effect waves-block"><i class="fa fa-home sidebar-icon"></i><span><span class="primery-color">@Html.ActionLink("Dashboard", "Index", "Home")</span></span></label> </li>
                    <li style="margin-bottom: -10px;"><label class="waves-effect waves-block"><i class="fa fa-file-o sidebar-icon"></i> @Html.ActionLink("Reports", "Index", "Facility")</label> </li>
                </ul>
            </div>
        </div>
        <footer style="text-align:center;font-size: 11px">
            <p>&copy; @DateTime.Now.Year - ZCS Asset Management</p>
        </footer>
    </div>
    <div class="container body-content  col-lg-10 col-md-10 col-sm-12">
        @RenderBody()
    </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/speedometer")
    @RenderSection("scripts", required: false)
    </body>
</html>

TheProject.ReportWebApplication/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ZCS Asset Management</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>   
    <div class="container body-content">
        @RenderBody()

        <footer style="text-align:center">
            <p>&copy; @DateTime.Now.Year - ZCS Asset Management</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TheProject.ReportWebApplication/Views/Shared/_NameSearch.cshtml
@model string

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-1.10.2.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("ul.filtroAlfab a").click(function (e) {
            $.ajax({
                url: this.href, success: function (data) {
                    $("#ajaxResponse").html(data);
                }
            });
            return false;
        });
    });
    $(function () {
        $("#from").datepicker();
        $("#to").datepicker();
    });
</script>
@using (Html.BeginForm("Search", Model))
{
    <div class="searchBox" style="margin-top: 5px;">
        <div class="row">
            <div class="col-md-6">
                <input name="search" id="search_Box" type="text" value="@Request["search"]"
                       placeholder="Facility" class="form-control" />
            </div>
            <div class="col-md-4">
                <input type="submit" value="Search" class="btn btn-info btn-sm" />
                <a href="?filter=clear" class="btn btn-default btn-sm">Refresh</a>
            </div>
        </div>
    </div>
}